# REST Client [Extension on Visual Studio Code]

@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@baseurl = http://{{host}}/api
# @contentType = application/json
# @createdAt = {{$datetime iso8601}}
# @modifiedBy = {{$processEnv USERNAME}}

GET {{baseurl}}/user HTTP/1.1

###

POST {{baseurl}}/auth/sign-in HTTP/1.1
content-type: application/json

{
    "email": "irwanto.regar30@gmail.com",
    "password": "secret123"
}

###

POST {{baseurl}}/auth/sign-up HTTP/1.1
content-type: application/json

{
    "name": "Taufik",
    "email": "taufik@gmail.com",
    "password": "secret123"
}